apiRules:
- exclude:
    uidRegex: ^i5.Toolkit.Core.Examples.*
    type: Namespace
- exclude:
    uidRegex: ^i5.Toolkit.Core.Tests.*
    type: Namespace
- exclude:
    uidRegex: ^InternalTools
    type: Namespace
- include:
    uidRegex: ^i5.*
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace