name: Unit Test Workflow

on:
  push:
    branches-ignore:
      # do not execute this on the master branch - we have a CI action for that
      - master
  pull_request:
    branches-ignore:
      # do not execute this on the master branch - we have a CI action for that
      - master

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testAllModes:
    name: Test in ${{ matrix.testMode }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        unityVersion:
          - 2018.4.15f1
        testMode:
          - playmode
          - editmode
    steps:
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
    
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
          restore-keys: |
            Library

      # Test
      - uses: webbertakken/unity-test-runner@v1.6
        id: tests
        with:
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          
      # Upload Test Results
      - uses: actions/upload-artifact@v1
        if: success() || failure()
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}